version: "2"

networks:
  default:
    external:
      name: matrix-network
services:
  web:
    container_name: matrix-ng
    image: nginx:latest
    ports:
        - "443:443"
    volumes:
        - /home/<username>/keys:/etc/matrix/:ro
        - /home/<username>/matrix/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  matrix:
    container_name: matrix
    image: silviof/docker-matrix
    # Exposing 8008 (no TLS) on localhost means we can reverse proxy with nginx
    # 8448 is for federation and should be exposed on host
    # 3478 is for TURN (voip calls)
    ports:
        - "8008:8008"
        - "8448:8448"
        - "3478:3478"
    volumes:
        - /home/<username>/matrix/data:/data
